### ISSUE TITLE
[Bug] Incorrect version `4.3.3` in `openbb_platform/pyproject.toml` for release `4.3.4`

### ISSUE THREAD

**Issue by the-praxs** [OpenBB-finance/OpenBB#6885]
**Describe the bug**

@deeleeramone @IgorWounds Pretty sure this is a minor mistake for the new release (#6870) -

```toml
[tool.poetry]
name = "openbb"
version = "4.3.3"
description = "Investment research for everyone, anywhere."
```
